<?php
/**
 * UpstreamsConfig
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AdGuard Home
 *
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API.
 *
 * OpenAPI spec version: 0.107
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * UpstreamsConfig Class Doc Comment
 *
 * @category Class
 * @description Upstreams configuration
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UpstreamsConfig implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UpstreamsConfig';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'bootstrap_dns' => 'string[]',
'upstream_dns' => 'string[]',
'private_upstream' => 'string[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'bootstrap_dns' => null,
'upstream_dns' => null,
'private_upstream' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bootstrap_dns' => 'bootstrap_dns',
'upstream_dns' => 'upstream_dns',
'private_upstream' => 'private_upstream'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bootstrap_dns' => 'setBootstrapDns',
'upstream_dns' => 'setUpstreamDns',
'private_upstream' => 'setPrivateUpstream'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bootstrap_dns' => 'getBootstrapDns',
'upstream_dns' => 'getUpstreamDns',
'private_upstream' => 'getPrivateUpstream'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['bootstrap_dns'] = isset($data['bootstrap_dns']) ? $data['bootstrap_dns'] : null;
        $this->container['upstream_dns'] = isset($data['upstream_dns']) ? $data['upstream_dns'] : null;
        $this->container['private_upstream'] = isset($data['private_upstream']) ? $data['private_upstream'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bootstrap_dns'] === null) {
            $invalidProperties[] = "'bootstrap_dns' can't be null";
        }
        if ($this->container['upstream_dns'] === null) {
            $invalidProperties[] = "'upstream_dns' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bootstrap_dns
     *
     * @return string[]
     */
    public function getBootstrapDns()
    {
        return $this->container['bootstrap_dns'];
    }

    /**
     * Sets bootstrap_dns
     *
     * @param string[] $bootstrap_dns Bootstrap servers, port is optional after colon.  Empty value will reset it to default values.
     *
     * @return $this
     */
    public function setBootstrapDns($bootstrap_dns)
    {
        $this->container['bootstrap_dns'] = $bootstrap_dns;

        return $this;
    }

    /**
     * Gets upstream_dns
     *
     * @return string[]
     */
    public function getUpstreamDns()
    {
        return $this->container['upstream_dns'];
    }

    /**
     * Sets upstream_dns
     *
     * @param string[] $upstream_dns Upstream servers, port is optional after colon.  Empty value will reset it to default values.
     *
     * @return $this
     */
    public function setUpstreamDns($upstream_dns)
    {
        $this->container['upstream_dns'] = $upstream_dns;

        return $this;
    }

    /**
     * Gets private_upstream
     *
     * @return string[]
     */
    public function getPrivateUpstream()
    {
        return $this->container['private_upstream'];
    }

    /**
     * Sets private_upstream
     *
     * @param string[] $private_upstream Local PTR resolvers, port is optional after colon.  Empty value will reset it to default values.
     *
     * @return $this
     */
    public function setPrivateUpstream($private_upstream)
    {
        $this->container['private_upstream'] = $private_upstream;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
