<?php
/**
 * ClientTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AdGuard Home
 *
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API.
 *
 * OpenAPI spec version: 0.107
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ClientTest Class Doc Comment
 *
 * @category    Class
 * @description Client information.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Client"
     */
    public function testClient()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "ids"
     */
    public function testPropertyIds()
    {
    }

    /**
     * Test attribute "use_global_settings"
     */
    public function testPropertyUseGlobalSettings()
    {
    }

    /**
     * Test attribute "filtering_enabled"
     */
    public function testPropertyFilteringEnabled()
    {
    }

    /**
     * Test attribute "parental_enabled"
     */
    public function testPropertyParentalEnabled()
    {
    }

    /**
     * Test attribute "safebrowsing_enabled"
     */
    public function testPropertySafebrowsingEnabled()
    {
    }

    /**
     * Test attribute "safesearch_enabled"
     */
    public function testPropertySafesearchEnabled()
    {
    }

    /**
     * Test attribute "use_global_blocked_services"
     */
    public function testPropertyUseGlobalBlockedServices()
    {
    }

    /**
     * Test attribute "blocked_services"
     */
    public function testPropertyBlockedServices()
    {
    }

    /**
     * Test attribute "upstreams"
     */
    public function testPropertyUpstreams()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }
}
