<?php
/**
 * DNSConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AdGuard Home
 *
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API.
 *
 * OpenAPI spec version: 0.107
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DNSConfigTest Class Doc Comment
 *
 * @category    Class
 * @description Query log configuration
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DNSConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DNSConfig"
     */
    public function testDNSConfig()
    {
    }

    /**
     * Test attribute "bootstrap_dns"
     */
    public function testPropertyBootstrapDns()
    {
    }

    /**
     * Test attribute "upstream_dns"
     */
    public function testPropertyUpstreamDns()
    {
    }

    /**
     * Test attribute "upstream_dns_file"
     */
    public function testPropertyUpstreamDnsFile()
    {
    }

    /**
     * Test attribute "protection_enabled"
     */
    public function testPropertyProtectionEnabled()
    {
    }

    /**
     * Test attribute "dhcp_available"
     */
    public function testPropertyDhcpAvailable()
    {
    }

    /**
     * Test attribute "ratelimit"
     */
    public function testPropertyRatelimit()
    {
    }

    /**
     * Test attribute "blocking_mode"
     */
    public function testPropertyBlockingMode()
    {
    }

    /**
     * Test attribute "blocking_ipv4"
     */
    public function testPropertyBlockingIpv4()
    {
    }

    /**
     * Test attribute "blocking_ipv6"
     */
    public function testPropertyBlockingIpv6()
    {
    }

    /**
     * Test attribute "edns_cs_enabled"
     */
    public function testPropertyEdnsCsEnabled()
    {
    }

    /**
     * Test attribute "disable_ipv6"
     */
    public function testPropertyDisableIpv6()
    {
    }

    /**
     * Test attribute "dnssec_enabled"
     */
    public function testPropertyDnssecEnabled()
    {
    }

    /**
     * Test attribute "cache_size"
     */
    public function testPropertyCacheSize()
    {
    }

    /**
     * Test attribute "cache_ttl_min"
     */
    public function testPropertyCacheTtlMin()
    {
    }

    /**
     * Test attribute "cache_ttl_max"
     */
    public function testPropertyCacheTtlMax()
    {
    }

    /**
     * Test attribute "cache_optimistic"
     */
    public function testPropertyCacheOptimistic()
    {
    }

    /**
     * Test attribute "upstream_mode"
     */
    public function testPropertyUpstreamMode()
    {
    }

    /**
     * Test attribute "use_private_ptr_resolvers"
     */
    public function testPropertyUsePrivatePtrResolvers()
    {
    }

    /**
     * Test attribute "resolve_clients"
     */
    public function testPropertyResolveClients()
    {
    }

    /**
     * Test attribute "local_ptr_upstreams"
     */
    public function testPropertyLocalPtrUpstreams()
    {
    }
}
