<?php
/**
 * TlsConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AdGuard Home
 *
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API.
 *
 * OpenAPI spec version: 0.107
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TlsConfigTest Class Doc Comment
 *
 * @category    Class
 * @description TLS configuration settings and status
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TlsConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TlsConfig"
     */
    public function testTlsConfig()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "force_https"
     */
    public function testPropertyForceHttps()
    {
    }

    /**
     * Test attribute "port_https"
     */
    public function testPropertyPortHttps()
    {
    }

    /**
     * Test attribute "port_dns_over_tls"
     */
    public function testPropertyPortDnsOverTls()
    {
    }

    /**
     * Test attribute "port_dns_over_quic"
     */
    public function testPropertyPortDnsOverQuic()
    {
    }

    /**
     * Test attribute "certificate_chain"
     */
    public function testPropertyCertificateChain()
    {
    }

    /**
     * Test attribute "private_key"
     */
    public function testPropertyPrivateKey()
    {
    }

    /**
     * Test attribute "private_key_saved"
     */
    public function testPropertyPrivateKeySaved()
    {
    }

    /**
     * Test attribute "certificate_path"
     */
    public function testPropertyCertificatePath()
    {
    }

    /**
     * Test attribute "private_key_path"
     */
    public function testPropertyPrivateKeyPath()
    {
    }

    /**
     * Test attribute "valid_cert"
     */
    public function testPropertyValidCert()
    {
    }

    /**
     * Test attribute "valid_chain"
     */
    public function testPropertyValidChain()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "issuer"
     */
    public function testPropertyIssuer()
    {
    }

    /**
     * Test attribute "not_before"
     */
    public function testPropertyNotBefore()
    {
    }

    /**
     * Test attribute "not_after"
     */
    public function testPropertyNotAfter()
    {
    }

    /**
     * Test attribute "dns_names"
     */
    public function testPropertyDnsNames()
    {
    }

    /**
     * Test attribute "valid_key"
     */
    public function testPropertyValidKey()
    {
    }

    /**
     * Test attribute "key_type"
     */
    public function testPropertyKeyType()
    {
    }

    /**
     * Test attribute "warning_validation"
     */
    public function testPropertyWarningValidation()
    {
    }

    /**
     * Test attribute "valid_pair"
     */
    public function testPropertyValidPair()
    {
    }
}
