<?php
/**
 * ClientsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AdGuard Home
 *
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API.
 *
 * OpenAPI spec version: 0.107
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ClientsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClientsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accessList
     *
     * List (dis)allowed clients, blocked hosts, etc..
     *
     */
    public function testAccessList()
    {
    }

    /**
     * Test case for accessSet
     *
     * Set (dis)allowed clients, blocked hosts, etc..
     *
     */
    public function testAccessSet()
    {
    }

    /**
     * Test case for clientsAdd
     *
     * Add a new client.
     *
     */
    public function testClientsAdd()
    {
    }

    /**
     * Test case for clientsDelete
     *
     * Remove a client.
     *
     */
    public function testClientsDelete()
    {
    }

    /**
     * Test case for clientsFind
     *
     * Get information about clients by their IP addresses or ClientIDs..
     *
     */
    public function testClientsFind()
    {
    }

    /**
     * Test case for clientsStatus
     *
     * Get information about configured clients.
     *
     */
    public function testClientsStatus()
    {
    }

    /**
     * Test case for clientsUpdate
     *
     * Update client information.
     *
     */
    public function testClientsUpdate()
    {
    }
}
