<?php
/**
 * FilteringApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AdGuard Home
 *
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API.
 *
 * OpenAPI spec version: 0.107
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * FilteringApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FilteringApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for filteringAddURL
     *
     * Add filter URL or an absolute file path.
     *
     */
    public function testFilteringAddURL()
    {
    }

    /**
     * Test case for filteringCheckHost
     *
     * Check if host name is filtered.
     *
     */
    public function testFilteringCheckHost()
    {
    }

    /**
     * Test case for filteringConfig
     *
     * Set filtering parameters.
     *
     */
    public function testFilteringConfig()
    {
    }

    /**
     * Test case for filteringRefresh
     *
     * Reload filtering rules from URLs.  This might be needed if new URL was just added and you don't want to wait for automatic refresh to kick in. This API request is ratelimited, so you can call it freely as often as you like, it wont create unnecessary burden on servers that host the URL.  This should work as intended, a `force` parameter is offered as last-resort attempt to make filter lists fresh.  If you ever find yourself using `force` to make something work that otherwise wont, this is a bug and report it accordingly..
     *
     */
    public function testFilteringRefresh()
    {
    }

    /**
     * Test case for filteringRemoveURL
     *
     * Remove filter URL.
     *
     */
    public function testFilteringRemoveURL()
    {
    }

    /**
     * Test case for filteringSetRules
     *
     * Set user-defined filter rules.
     *
     */
    public function testFilteringSetRules()
    {
    }

    /**
     * Test case for filteringSetURL
     *
     * Set URL parameters.
     *
     */
    public function testFilteringSetURL()
    {
    }

    /**
     * Test case for filteringStatus
     *
     * Get filtering parameters.
     *
     */
    public function testFilteringStatus()
    {
    }
}
