<?php
/**
 * InstallApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AdGuard Home
 *
 * AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API.
 *
 * OpenAPI spec version: 0.107
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * InstallApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstallApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for installCheckConfig
     *
     * Checks configuration.
     *
     */
    public function testInstallCheckConfig()
    {
    }

    /**
     * Test case for installCheckConfigBeta
     *
     * 'UNSTABLE!: Checks configuration'.
     *
     */
    public function testInstallCheckConfigBeta()
    {
    }

    /**
     * Test case for installConfigure
     *
     * Applies the initial configuration..
     *
     */
    public function testInstallConfigure()
    {
    }

    /**
     * Test case for installConfigureBeta
     *
     * 'UNSTABLE!: Applies the initial configuration.'.
     *
     */
    public function testInstallConfigureBeta()
    {
    }

    /**
     * Test case for installGetAddresses
     *
     * Gets the network interfaces information..
     *
     */
    public function testInstallGetAddresses()
    {
    }

    /**
     * Test case for installGetAddressesBeta
     *
     * 'UNSTABLE!: Gets the network interfaces information.'.
     *
     */
    public function testInstallGetAddressesBeta()
    {
    }
}
